'use client'

import type { Scene, Emotion } from '@/lib/types'

interface SceneCardProps {
  scene: Scene
  index: number
  isPlaying: boolean
  onClick: () => void
}

const emotionColors: Record<Emotion, string> = {
  triumph: '#f97316',
  frustration: '#ef4444',
  hope: '#3b82f6',
  excitement: '#eab308',
  despair: '#6b7280',
  curiosity: '#a855f7',
  relief: '#22c55e',
  determination: '#f59e0b',
  neutral: '#9ca3af',
}

export function SceneCard({ scene, index, isPlaying, onClick }: SceneCardProps) {
  return (
    <div
      className={`scene-card ${isPlaying ? 'playing' : ''}`}
      onClick={onClick}
      role="button"
      tabIndex={0}
      onKeyDown={(e) => {
        if (e.key === 'Enter' || e.key === ' ') {
          e.preventDefault()
          onClick()
        }
      }}
    >
      <div className="scene-number">Scene {index + 1}</div>
      <div className="svg-container">
        {/* SVG content is intentionally rendered with dangerouslySetInnerHTML 
            as it's generated by our controlled AI backend */}
        <div dangerouslySetInnerHTML={{ __html: scene.svgScene }} />
      </div>
      <div className="scene-content">
        <p className="scene-sentence">{scene.sentence}</p>
        <div className="scene-meta">
          <span
            className="emotion-badge"
            style={{ backgroundColor: emotionColors[scene.emotion] }}
          >
            {scene.emotion}
          </span>
          <span className="character-count">
            {scene.characters} {scene.characters === 1 ? 'character' : 'characters'}
          </span>
        </div>
      </div>
      {isPlaying && (
        <div className="playing-indicator">
          <span className="wave-bar" />
          <span className="wave-bar" />
          <span className="wave-bar" />
        </div>
      )}
    </div>
  )
}
