export type GameplayChunk = { index: number; url: string; durationSec: number }

export type GameplayVideo = {
  id: string
  label: string
  thumbnailUrl: string
  chunks: GameplayChunk[]
}

export type GameplayCategory = {
  id: string
  label: string
  thumbnailUrl: string
  videos: GameplayVideo[]
}

/** Auto-generated by pnpm ingest:brainrot — do not edit by hand. */
export const GAMEPLAY_CATALOG: GameplayCategory[] = [
  {
    "id": "minecraft",
    "label": "Minecraft",
    "thumbnailUrl": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-02/chunk-00.mp4",
    "videos": [
      {
        "id": "brainrot-template-minecraft-02",
        "label": "Brainrot Template 02",
        "thumbnailUrl": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-02/chunk-00.mp4",
        "chunks": [
          {
            "index": 0,
            "url": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-02/chunk-00.mp4",
            "durationSec": 30
          },
          {
            "index": 1,
            "url": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-02/chunk-01.mp4",
            "durationSec": 30
          },
          {
            "index": 2,
            "url": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-02/chunk-02.mp4",
            "durationSec": 30
          },
          {
            "index": 3,
            "url": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-02/chunk-03.mp4",
            "durationSec": 30
          },
          {
            "index": 4,
            "url": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-02/chunk-04.mp4",
            "durationSec": 30
          },
          {
            "index": 5,
            "url": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-02/chunk-05.mp4",
            "durationSec": 30
          },
          {
            "index": 6,
            "url": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-02/chunk-06.mp4",
            "durationSec": 30
          },
          {
            "index": 7,
            "url": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-02/chunk-07.mp4",
            "durationSec": 30
          },
          {
            "index": 8,
            "url": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-02/chunk-08.mp4",
            "durationSec": 30
          },
          {
            "index": 9,
            "url": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-02/chunk-09.mp4",
            "durationSec": 30
          },
          {
            "index": 10,
            "url": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-02/chunk-10.mp4",
            "durationSec": 30
          },
          {
            "index": 11,
            "url": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-02/chunk-11.mp4",
            "durationSec": 30
          },
          {
            "index": 12,
            "url": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-02/chunk-12.mp4",
            "durationSec": 30
          },
          {
            "index": 13,
            "url": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-02/chunk-13.mp4",
            "durationSec": 30
          },
          {
            "index": 14,
            "url": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-02/chunk-14.mp4",
            "durationSec": 30
          },
          {
            "index": 15,
            "url": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-02/chunk-15.mp4",
            "durationSec": 30
          },
          {
            "index": 16,
            "url": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-02/chunk-16.mp4",
            "durationSec": 30
          },
          {
            "index": 17,
            "url": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-02/chunk-17.mp4",
            "durationSec": 30
          },
          {
            "index": 18,
            "url": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-02/chunk-18.mp4",
            "durationSec": 30
          },
          {
            "index": 19,
            "url": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-02/chunk-19.mp4",
            "durationSec": 30
          },
          {
            "index": 20,
            "url": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-02/chunk-20.mp4",
            "durationSec": 30
          }
        ]
      },
      {
        "id": "brainrot-template-minecraft-03",
        "label": "Brainrot Template 03",
        "thumbnailUrl": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-03/chunk-00.mp4",
        "chunks": [
          {
            "index": 0,
            "url": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-03/chunk-00.mp4",
            "durationSec": 30
          },
          {
            "index": 1,
            "url": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-03/chunk-01.mp4",
            "durationSec": 30
          },
          {
            "index": 2,
            "url": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-03/chunk-02.mp4",
            "durationSec": 30
          },
          {
            "index": 3,
            "url": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-03/chunk-03.mp4",
            "durationSec": 30
          },
          {
            "index": 4,
            "url": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-03/chunk-04.mp4",
            "durationSec": 30
          },
          {
            "index": 5,
            "url": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-03/chunk-05.mp4",
            "durationSec": 30
          },
          {
            "index": 6,
            "url": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-03/chunk-06.mp4",
            "durationSec": 30
          },
          {
            "index": 7,
            "url": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-03/chunk-07.mp4",
            "durationSec": 30
          },
          {
            "index": 8,
            "url": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-03/chunk-08.mp4",
            "durationSec": 30
          },
          {
            "index": 9,
            "url": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-03/chunk-09.mp4",
            "durationSec": 30
          }
        ]
      },
      {
        "id": "brainrot-template-minecraft-04",
        "label": "Brainrot Template 04",
        "thumbnailUrl": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-04/chunk-00.mp4",
        "chunks": [
          {
            "index": 0,
            "url": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-04/chunk-00.mp4",
            "durationSec": 30
          },
          {
            "index": 1,
            "url": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-04/chunk-01.mp4",
            "durationSec": 30
          },
          {
            "index": 2,
            "url": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-04/chunk-02.mp4",
            "durationSec": 30
          },
          {
            "index": 3,
            "url": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-04/chunk-03.mp4",
            "durationSec": 30
          },
          {
            "index": 4,
            "url": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-04/chunk-04.mp4",
            "durationSec": 30
          },
          {
            "index": 5,
            "url": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-04/chunk-05.mp4",
            "durationSec": 30
          },
          {
            "index": 6,
            "url": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-04/chunk-06.mp4",
            "durationSec": 30
          },
          {
            "index": 7,
            "url": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-04/chunk-07.mp4",
            "durationSec": 30
          },
          {
            "index": 8,
            "url": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-04/chunk-08.mp4",
            "durationSec": 30
          },
          {
            "index": 9,
            "url": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-04/chunk-09.mp4",
            "durationSec": 30
          },
          {
            "index": 10,
            "url": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-04/chunk-10.mp4",
            "durationSec": 30
          },
          {
            "index": 11,
            "url": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-04/chunk-11.mp4",
            "durationSec": 30
          },
          {
            "index": 12,
            "url": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-04/chunk-12.mp4",
            "durationSec": 30
          },
          {
            "index": 13,
            "url": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-04/chunk-13.mp4",
            "durationSec": 30
          },
          {
            "index": 14,
            "url": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-04/chunk-14.mp4",
            "durationSec": 30
          },
          {
            "index": 15,
            "url": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-04/chunk-15.mp4",
            "durationSec": 30
          },
          {
            "index": 16,
            "url": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-04/chunk-16.mp4",
            "durationSec": 30
          },
          {
            "index": 17,
            "url": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-04/chunk-17.mp4",
            "durationSec": 30
          },
          {
            "index": 18,
            "url": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-04/chunk-18.mp4",
            "durationSec": 30
          },
          {
            "index": 19,
            "url": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-04/chunk-19.mp4",
            "durationSec": 30
          },
          {
            "index": 20,
            "url": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-04/chunk-20.mp4",
            "durationSec": 30
          }
        ]
      },
      {
        "id": "brainrot-template-minecraft-05",
        "label": "Brainrot Template 05",
        "thumbnailUrl": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-05/chunk-00.mp4",
        "chunks": [
          {
            "index": 0,
            "url": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-05/chunk-00.mp4",
            "durationSec": 30
          },
          {
            "index": 1,
            "url": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-05/chunk-01.mp4",
            "durationSec": 30
          },
          {
            "index": 2,
            "url": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-05/chunk-02.mp4",
            "durationSec": 30
          },
          {
            "index": 3,
            "url": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-05/chunk-03.mp4",
            "durationSec": 30
          },
          {
            "index": 4,
            "url": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-05/chunk-04.mp4",
            "durationSec": 30
          },
          {
            "index": 5,
            "url": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-05/chunk-05.mp4",
            "durationSec": 30
          },
          {
            "index": 6,
            "url": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-05/chunk-06.mp4",
            "durationSec": 30
          },
          {
            "index": 7,
            "url": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-05/chunk-07.mp4",
            "durationSec": 30
          },
          {
            "index": 8,
            "url": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-05/chunk-08.mp4",
            "durationSec": 30
          },
          {
            "index": 9,
            "url": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-05/chunk-09.mp4",
            "durationSec": 30
          },
          {
            "index": 10,
            "url": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-05/chunk-10.mp4",
            "durationSec": 30
          },
          {
            "index": 11,
            "url": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-05/chunk-11.mp4",
            "durationSec": 30
          }
        ]
      },
      {
        "id": "brainrot-template-minecraft-06",
        "label": "Brainrot Template 06",
        "thumbnailUrl": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-06/thumb.jpg",
        "chunks": [
          {
            "index": 0,
            "url": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-06/chunk-00.mp4",
            "durationSec": 30
          },
          {
            "index": 1,
            "url": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-06/chunk-01.mp4",
            "durationSec": 30
          },
          {
            "index": 2,
            "url": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-06/chunk-02.mp4",
            "durationSec": 30
          },
          {
            "index": 3,
            "url": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-06/chunk-03.mp4",
            "durationSec": 30
          },
          {
            "index": 4,
            "url": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-06/chunk-04.mp4",
            "durationSec": 30
          },
          {
            "index": 5,
            "url": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-06/chunk-05.mp4",
            "durationSec": 30
          },
          {
            "index": 6,
            "url": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-06/chunk-06.mp4",
            "durationSec": 30
          },
          {
            "index": 7,
            "url": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-06/chunk-07.mp4",
            "durationSec": 30
          },
          {
            "index": 8,
            "url": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-06/chunk-08.mp4",
            "durationSec": 30
          },
          {
            "index": 9,
            "url": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-06/chunk-09.mp4",
            "durationSec": 30
          },
          {
            "index": 10,
            "url": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-06/chunk-10.mp4",
            "durationSec": 30
          },
          {
            "index": 11,
            "url": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-06/chunk-11.mp4",
            "durationSec": 30
          },
          {
            "index": 12,
            "url": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-06/chunk-12.mp4",
            "durationSec": 30
          },
          {
            "index": 13,
            "url": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-06/chunk-13.mp4",
            "durationSec": 30
          },
          {
            "index": 14,
            "url": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-06/chunk-14.mp4",
            "durationSec": 30
          },
          {
            "index": 15,
            "url": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-06/chunk-15.mp4",
            "durationSec": 30
          },
          {
            "index": 16,
            "url": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-06/chunk-16.mp4",
            "durationSec": 30
          },
          {
            "index": 17,
            "url": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-06/chunk-17.mp4",
            "durationSec": 30
          },
          {
            "index": 18,
            "url": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-06/chunk-18.mp4",
            "durationSec": 30
          },
          {
            "index": 19,
            "url": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-06/chunk-19.mp4",
            "durationSec": 30
          },
          {
            "index": 20,
            "url": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-06/chunk-20.mp4",
            "durationSec": 30
          },
          {
            "index": 21,
            "url": "https://cdn.reelfyme.com/brainrot-template/minecraft/template-06/chunk-21.mp4",
            "durationSec": 30
          }
        ]
      }
    ]
  },
  {
    "id": "subway-surfers",
    "label": "Subway Surfers",
    "thumbnailUrl": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/thumb.jpg",
    "videos": [
      {
        "id": "subway-surfers",
        "label": "Subway Surfers",
        "thumbnailUrl": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/thumb.jpg",
        "chunks": [
          {
            "index": 0,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-00.mp4",
            "durationSec": 30
          },
          {
            "index": 1,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-01.mp4",
            "durationSec": 30
          },
          {
            "index": 2,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-02.mp4",
            "durationSec": 30
          },
          {
            "index": 3,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-03.mp4",
            "durationSec": 30
          },
          {
            "index": 4,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-04.mp4",
            "durationSec": 30
          },
          {
            "index": 5,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-05.mp4",
            "durationSec": 30
          },
          {
            "index": 6,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-06.mp4",
            "durationSec": 30
          },
          {
            "index": 7,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-07.mp4",
            "durationSec": 30
          },
          {
            "index": 8,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-08.mp4",
            "durationSec": 30
          },
          {
            "index": 9,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-09.mp4",
            "durationSec": 30
          },
          {
            "index": 10,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-10.mp4",
            "durationSec": 30
          },
          {
            "index": 11,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-11.mp4",
            "durationSec": 30
          },
          {
            "index": 12,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-12.mp4",
            "durationSec": 30
          },
          {
            "index": 13,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-13.mp4",
            "durationSec": 30
          },
          {
            "index": 14,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-14.mp4",
            "durationSec": 30
          },
          {
            "index": 15,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-15.mp4",
            "durationSec": 30
          },
          {
            "index": 16,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-16.mp4",
            "durationSec": 30
          },
          {
            "index": 17,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-17.mp4",
            "durationSec": 30
          },
          {
            "index": 18,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-18.mp4",
            "durationSec": 30
          },
          {
            "index": 19,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-19.mp4",
            "durationSec": 30
          },
          {
            "index": 20,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-20.mp4",
            "durationSec": 30
          },
          {
            "index": 21,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-21.mp4",
            "durationSec": 30
          },
          {
            "index": 22,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-22.mp4",
            "durationSec": 30
          },
          {
            "index": 23,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-23.mp4",
            "durationSec": 30
          },
          {
            "index": 24,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-24.mp4",
            "durationSec": 30
          },
          {
            "index": 25,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-25.mp4",
            "durationSec": 30
          },
          {
            "index": 26,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-26.mp4",
            "durationSec": 30
          },
          {
            "index": 27,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-27.mp4",
            "durationSec": 30
          },
          {
            "index": 28,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-28.mp4",
            "durationSec": 30
          },
          {
            "index": 29,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-29.mp4",
            "durationSec": 30
          },
          {
            "index": 30,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-30.mp4",
            "durationSec": 30
          },
          {
            "index": 31,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-31.mp4",
            "durationSec": 30
          },
          {
            "index": 32,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-32.mp4",
            "durationSec": 30
          },
          {
            "index": 33,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-33.mp4",
            "durationSec": 30
          },
          {
            "index": 34,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-34.mp4",
            "durationSec": 30
          },
          {
            "index": 35,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-35.mp4",
            "durationSec": 30
          },
          {
            "index": 36,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-36.mp4",
            "durationSec": 30
          },
          {
            "index": 37,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-37.mp4",
            "durationSec": 30
          },
          {
            "index": 38,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-38.mp4",
            "durationSec": 30
          },
          {
            "index": 39,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-39.mp4",
            "durationSec": 30
          },
          {
            "index": 40,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-40.mp4",
            "durationSec": 30
          },
          {
            "index": 41,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-41.mp4",
            "durationSec": 30
          },
          {
            "index": 42,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-42.mp4",
            "durationSec": 30
          },
          {
            "index": 43,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-43.mp4",
            "durationSec": 30
          },
          {
            "index": 44,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-44.mp4",
            "durationSec": 30
          },
          {
            "index": 45,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-45.mp4",
            "durationSec": 30
          },
          {
            "index": 46,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-46.mp4",
            "durationSec": 30
          },
          {
            "index": 47,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-47.mp4",
            "durationSec": 30
          },
          {
            "index": 48,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-48.mp4",
            "durationSec": 30
          },
          {
            "index": 49,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-49.mp4",
            "durationSec": 30
          },
          {
            "index": 50,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-50.mp4",
            "durationSec": 30
          },
          {
            "index": 51,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-51.mp4",
            "durationSec": 30
          },
          {
            "index": 52,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-52.mp4",
            "durationSec": 30
          },
          {
            "index": 53,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-53.mp4",
            "durationSec": 30
          },
          {
            "index": 54,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-54.mp4",
            "durationSec": 30
          },
          {
            "index": 55,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-55.mp4",
            "durationSec": 30
          },
          {
            "index": 56,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-56.mp4",
            "durationSec": 30
          },
          {
            "index": 57,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-57.mp4",
            "durationSec": 30
          },
          {
            "index": 58,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-58.mp4",
            "durationSec": 30
          },
          {
            "index": 59,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-59.mp4",
            "durationSec": 30
          },
          {
            "index": 60,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-60.mp4",
            "durationSec": 30
          },
          {
            "index": 61,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-61.mp4",
            "durationSec": 30
          },
          {
            "index": 62,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-62.mp4",
            "durationSec": 30
          },
          {
            "index": 63,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-63.mp4",
            "durationSec": 30
          },
          {
            "index": 64,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-64.mp4",
            "durationSec": 30
          },
          {
            "index": 65,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-65.mp4",
            "durationSec": 30
          },
          {
            "index": 66,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-66.mp4",
            "durationSec": 30
          },
          {
            "index": 67,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-67.mp4",
            "durationSec": 30
          },
          {
            "index": 68,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-68.mp4",
            "durationSec": 30
          },
          {
            "index": 69,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-69.mp4",
            "durationSec": 30
          },
          {
            "index": 70,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-70.mp4",
            "durationSec": 30
          },
          {
            "index": 71,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-71.mp4",
            "durationSec": 30
          },
          {
            "index": 72,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-72.mp4",
            "durationSec": 30
          },
          {
            "index": 73,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-73.mp4",
            "durationSec": 30
          },
          {
            "index": 74,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-74.mp4",
            "durationSec": 30
          },
          {
            "index": 75,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-75.mp4",
            "durationSec": 30
          },
          {
            "index": 76,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-76.mp4",
            "durationSec": 30
          },
          {
            "index": 77,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-77.mp4",
            "durationSec": 30
          },
          {
            "index": 78,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-78.mp4",
            "durationSec": 30
          },
          {
            "index": 79,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-79.mp4",
            "durationSec": 30
          },
          {
            "index": 80,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-80.mp4",
            "durationSec": 30
          },
          {
            "index": 81,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-81.mp4",
            "durationSec": 30
          },
          {
            "index": 82,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-82.mp4",
            "durationSec": 30
          },
          {
            "index": 83,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-83.mp4",
            "durationSec": 30
          },
          {
            "index": 84,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-84.mp4",
            "durationSec": 30
          },
          {
            "index": 85,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-85.mp4",
            "durationSec": 30
          },
          {
            "index": 86,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-86.mp4",
            "durationSec": 30
          },
          {
            "index": 87,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-87.mp4",
            "durationSec": 30
          },
          {
            "index": 88,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-88.mp4",
            "durationSec": 30
          },
          {
            "index": 89,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-89.mp4",
            "durationSec": 30
          },
          {
            "index": 90,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-90.mp4",
            "durationSec": 30
          },
          {
            "index": 91,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-91.mp4",
            "durationSec": 30
          },
          {
            "index": 92,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-92.mp4",
            "durationSec": 30
          },
          {
            "index": 93,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-93.mp4",
            "durationSec": 30
          },
          {
            "index": 94,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-94.mp4",
            "durationSec": 30
          },
          {
            "index": 95,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-95.mp4",
            "durationSec": 30
          },
          {
            "index": 96,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-96.mp4",
            "durationSec": 30
          },
          {
            "index": 97,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-97.mp4",
            "durationSec": 30
          },
          {
            "index": 98,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-98.mp4",
            "durationSec": 30
          },
          {
            "index": 99,
            "url": "https://cdn.reelfyme.com/brainrot-template/subway-surfers/chunk-99.mp4",
            "durationSec": 30
          }
        ]
      }
    ]
  },
  {
    "id": "valorant",
    "label": "Valorant",
    "thumbnailUrl": "https://cdn.reelfyme.com/brainrot-template/valorant/thumb.jpg",
    "videos": [
      {
        "id": "valorant",
        "label": "Valorant",
        "thumbnailUrl": "https://cdn.reelfyme.com/brainrot-template/valorant/thumb.jpg",
        "chunks": [
          {
            "index": 0,
            "url": "https://cdn.reelfyme.com/brainrot-template/valorant/chunk-00.mp4",
            "durationSec": 30
          },
          {
            "index": 1,
            "url": "https://cdn.reelfyme.com/brainrot-template/valorant/chunk-01.mp4",
            "durationSec": 30
          },
          {
            "index": 2,
            "url": "https://cdn.reelfyme.com/brainrot-template/valorant/chunk-02.mp4",
            "durationSec": 30
          },
          {
            "index": 3,
            "url": "https://cdn.reelfyme.com/brainrot-template/valorant/chunk-03.mp4",
            "durationSec": 30
          },
          {
            "index": 4,
            "url": "https://cdn.reelfyme.com/brainrot-template/valorant/chunk-04.mp4",
            "durationSec": 30
          },
          {
            "index": 5,
            "url": "https://cdn.reelfyme.com/brainrot-template/valorant/chunk-05.mp4",
            "durationSec": 30
          },
          {
            "index": 6,
            "url": "https://cdn.reelfyme.com/brainrot-template/valorant/chunk-06.mp4",
            "durationSec": 30
          },
          {
            "index": 7,
            "url": "https://cdn.reelfyme.com/brainrot-template/valorant/chunk-07.mp4",
            "durationSec": 30
          },
          {
            "index": 8,
            "url": "https://cdn.reelfyme.com/brainrot-template/valorant/chunk-08.mp4",
            "durationSec": 30
          },
          {
            "index": 9,
            "url": "https://cdn.reelfyme.com/brainrot-template/valorant/chunk-09.mp4",
            "durationSec": 30
          },
          {
            "index": 10,
            "url": "https://cdn.reelfyme.com/brainrot-template/valorant/chunk-10.mp4",
            "durationSec": 30
          },
          {
            "index": 11,
            "url": "https://cdn.reelfyme.com/brainrot-template/valorant/chunk-11.mp4",
            "durationSec": 30
          },
          {
            "index": 12,
            "url": "https://cdn.reelfyme.com/brainrot-template/valorant/chunk-12.mp4",
            "durationSec": 30
          },
          {
            "index": 13,
            "url": "https://cdn.reelfyme.com/brainrot-template/valorant/chunk-13.mp4",
            "durationSec": 30
          },
          {
            "index": 14,
            "url": "https://cdn.reelfyme.com/brainrot-template/valorant/chunk-14.mp4",
            "durationSec": 30
          },
          {
            "index": 15,
            "url": "https://cdn.reelfyme.com/brainrot-template/valorant/chunk-15.mp4",
            "durationSec": 30
          },
          {
            "index": 16,
            "url": "https://cdn.reelfyme.com/brainrot-template/valorant/chunk-16.mp4",
            "durationSec": 30
          },
          {
            "index": 17,
            "url": "https://cdn.reelfyme.com/brainrot-template/valorant/chunk-17.mp4",
            "durationSec": 30
          },
          {
            "index": 18,
            "url": "https://cdn.reelfyme.com/brainrot-template/valorant/chunk-18.mp4",
            "durationSec": 30
          },
          {
            "index": 19,
            "url": "https://cdn.reelfyme.com/brainrot-template/valorant/chunk-19.mp4",
            "durationSec": 30
          },
          {
            "index": 20,
            "url": "https://cdn.reelfyme.com/brainrot-template/valorant/chunk-20.mp4",
            "durationSec": 30
          },
          {
            "index": 21,
            "url": "https://cdn.reelfyme.com/brainrot-template/valorant/chunk-21.mp4",
            "durationSec": 30
          },
          {
            "index": 22,
            "url": "https://cdn.reelfyme.com/brainrot-template/valorant/chunk-22.mp4",
            "durationSec": 30
          },
          {
            "index": 23,
            "url": "https://cdn.reelfyme.com/brainrot-template/valorant/chunk-23.mp4",
            "durationSec": 30
          },
          {
            "index": 24,
            "url": "https://cdn.reelfyme.com/brainrot-template/valorant/chunk-24.mp4",
            "durationSec": 30
          },
          {
            "index": 25,
            "url": "https://cdn.reelfyme.com/brainrot-template/valorant/chunk-25.mp4",
            "durationSec": 30
          },
          {
            "index": 26,
            "url": "https://cdn.reelfyme.com/brainrot-template/valorant/chunk-26.mp4",
            "durationSec": 30
          },
          {
            "index": 27,
            "url": "https://cdn.reelfyme.com/brainrot-template/valorant/chunk-27.mp4",
            "durationSec": 30
          },
          {
            "index": 28,
            "url": "https://cdn.reelfyme.com/brainrot-template/valorant/chunk-28.mp4",
            "durationSec": 30
          },
          {
            "index": 29,
            "url": "https://cdn.reelfyme.com/brainrot-template/valorant/chunk-29.mp4",
            "durationSec": 30
          },
          {
            "index": 30,
            "url": "https://cdn.reelfyme.com/brainrot-template/valorant/chunk-30.mp4",
            "durationSec": 30
          },
          {
            "index": 31,
            "url": "https://cdn.reelfyme.com/brainrot-template/valorant/chunk-31.mp4",
            "durationSec": 30
          },
          {
            "index": 32,
            "url": "https://cdn.reelfyme.com/brainrot-template/valorant/chunk-32.mp4",
            "durationSec": 30
          },
          {
            "index": 33,
            "url": "https://cdn.reelfyme.com/brainrot-template/valorant/chunk-33.mp4",
            "durationSec": 30
          },
          {
            "index": 34,
            "url": "https://cdn.reelfyme.com/brainrot-template/valorant/chunk-34.mp4",
            "durationSec": 30
          },
          {
            "index": 35,
            "url": "https://cdn.reelfyme.com/brainrot-template/valorant/chunk-35.mp4",
            "durationSec": 30
          },
          {
            "index": 36,
            "url": "https://cdn.reelfyme.com/brainrot-template/valorant/chunk-36.mp4",
            "durationSec": 30
          },
          {
            "index": 37,
            "url": "https://cdn.reelfyme.com/brainrot-template/valorant/chunk-37.mp4",
            "durationSec": 30
          },
          {
            "index": 38,
            "url": "https://cdn.reelfyme.com/brainrot-template/valorant/chunk-38.mp4",
            "durationSec": 30
          },
          {
            "index": 39,
            "url": "https://cdn.reelfyme.com/brainrot-template/valorant/chunk-39.mp4",
            "durationSec": 30
          },
          {
            "index": 40,
            "url": "https://cdn.reelfyme.com/brainrot-template/valorant/chunk-40.mp4",
            "durationSec": 30
          },
          {
            "index": 41,
            "url": "https://cdn.reelfyme.com/brainrot-template/valorant/chunk-41.mp4",
            "durationSec": 30
          },
          {
            "index": 42,
            "url": "https://cdn.reelfyme.com/brainrot-template/valorant/chunk-42.mp4",
            "durationSec": 30
          },
          {
            "index": 43,
            "url": "https://cdn.reelfyme.com/brainrot-template/valorant/chunk-43.mp4",
            "durationSec": 30
          },
          {
            "index": 44,
            "url": "https://cdn.reelfyme.com/brainrot-template/valorant/chunk-44.mp4",
            "durationSec": 30
          },
          {
            "index": 45,
            "url": "https://cdn.reelfyme.com/brainrot-template/valorant/chunk-45.mp4",
            "durationSec": 30
          },
          {
            "index": 46,
            "url": "https://cdn.reelfyme.com/brainrot-template/valorant/chunk-46.mp4",
            "durationSec": 30
          },
          {
            "index": 47,
            "url": "https://cdn.reelfyme.com/brainrot-template/valorant/chunk-47.mp4",
            "durationSec": 30
          },
          {
            "index": 48,
            "url": "https://cdn.reelfyme.com/brainrot-template/valorant/chunk-48.mp4",
            "durationSec": 30
          },
          {
            "index": 49,
            "url": "https://cdn.reelfyme.com/brainrot-template/valorant/chunk-49.mp4",
            "durationSec": 30
          },
          {
            "index": 50,
            "url": "https://cdn.reelfyme.com/brainrot-template/valorant/chunk-50.mp4",
            "durationSec": 30
          },
          {
            "index": 51,
            "url": "https://cdn.reelfyme.com/brainrot-template/valorant/chunk-51.mp4",
            "durationSec": 30
          },
          {
            "index": 52,
            "url": "https://cdn.reelfyme.com/brainrot-template/valorant/chunk-52.mp4",
            "durationSec": 30
          },
          {
            "index": 53,
            "url": "https://cdn.reelfyme.com/brainrot-template/valorant/chunk-53.mp4",
            "durationSec": 30
          },
          {
            "index": 54,
            "url": "https://cdn.reelfyme.com/brainrot-template/valorant/chunk-54.mp4",
            "durationSec": 30
          },
          {
            "index": 55,
            "url": "https://cdn.reelfyme.com/brainrot-template/valorant/chunk-55.mp4",
            "durationSec": 30
          },
          {
            "index": 56,
            "url": "https://cdn.reelfyme.com/brainrot-template/valorant/chunk-56.mp4",
            "durationSec": 30
          },
          {
            "index": 57,
            "url": "https://cdn.reelfyme.com/brainrot-template/valorant/chunk-57.mp4",
            "durationSec": 30
          },
          {
            "index": 58,
            "url": "https://cdn.reelfyme.com/brainrot-template/valorant/chunk-58.mp4",
            "durationSec": 30
          },
          {
            "index": 59,
            "url": "https://cdn.reelfyme.com/brainrot-template/valorant/chunk-59.mp4",
            "durationSec": 30
          },
          {
            "index": 60,
            "url": "https://cdn.reelfyme.com/brainrot-template/valorant/chunk-60.mp4",
            "durationSec": 30
          },
          {
            "index": 61,
            "url": "https://cdn.reelfyme.com/brainrot-template/valorant/chunk-61.mp4",
            "durationSec": 30
          },
          {
            "index": 62,
            "url": "https://cdn.reelfyme.com/brainrot-template/valorant/chunk-62.mp4",
            "durationSec": 30
          },
          {
            "index": 63,
            "url": "https://cdn.reelfyme.com/brainrot-template/valorant/chunk-63.mp4",
            "durationSec": 30
          },
          {
            "index": 64,
            "url": "https://cdn.reelfyme.com/brainrot-template/valorant/chunk-64.mp4",
            "durationSec": 30
          },
          {
            "index": 65,
            "url": "https://cdn.reelfyme.com/brainrot-template/valorant/chunk-65.mp4",
            "durationSec": 30
          },
          {
            "index": 66,
            "url": "https://cdn.reelfyme.com/brainrot-template/valorant/chunk-66.mp4",
            "durationSec": 30
          },
          {
            "index": 67,
            "url": "https://cdn.reelfyme.com/brainrot-template/valorant/chunk-67.mp4",
            "durationSec": 30
          },
          {
            "index": 68,
            "url": "https://cdn.reelfyme.com/brainrot-template/valorant/chunk-68.mp4",
            "durationSec": 30
          },
          {
            "index": 69,
            "url": "https://cdn.reelfyme.com/brainrot-template/valorant/chunk-69.mp4",
            "durationSec": 30
          },
          {
            "index": 70,
            "url": "https://cdn.reelfyme.com/brainrot-template/valorant/chunk-70.mp4",
            "durationSec": 30
          },
          {
            "index": 71,
            "url": "https://cdn.reelfyme.com/brainrot-template/valorant/chunk-71.mp4",
            "durationSec": 30
          },
          {
            "index": 72,
            "url": "https://cdn.reelfyme.com/brainrot-template/valorant/chunk-72.mp4",
            "durationSec": 30
          },
          {
            "index": 73,
            "url": "https://cdn.reelfyme.com/brainrot-template/valorant/chunk-73.mp4",
            "durationSec": 30
          },
          {
            "index": 74,
            "url": "https://cdn.reelfyme.com/brainrot-template/valorant/chunk-74.mp4",
            "durationSec": 30
          },
          {
            "index": 75,
            "url": "https://cdn.reelfyme.com/brainrot-template/valorant/chunk-75.mp4",
            "durationSec": 30
          },
          {
            "index": 76,
            "url": "https://cdn.reelfyme.com/brainrot-template/valorant/chunk-76.mp4",
            "durationSec": 30
          },
          {
            "index": 77,
            "url": "https://cdn.reelfyme.com/brainrot-template/valorant/chunk-77.mp4",
            "durationSec": 30
          },
          {
            "index": 78,
            "url": "https://cdn.reelfyme.com/brainrot-template/valorant/chunk-78.mp4",
            "durationSec": 30
          },
          {
            "index": 79,
            "url": "https://cdn.reelfyme.com/brainrot-template/valorant/chunk-79.mp4",
            "durationSec": 30
          },
          {
            "index": 80,
            "url": "https://cdn.reelfyme.com/brainrot-template/valorant/chunk-80.mp4",
            "durationSec": 30
          },
          {
            "index": 81,
            "url": "https://cdn.reelfyme.com/brainrot-template/valorant/chunk-81.mp4",
            "durationSec": 30
          },
          {
            "index": 82,
            "url": "https://cdn.reelfyme.com/brainrot-template/valorant/chunk-82.mp4",
            "durationSec": 30
          },
          {
            "index": 83,
            "url": "https://cdn.reelfyme.com/brainrot-template/valorant/chunk-83.mp4",
            "durationSec": 30
          },
          {
            "index": 84,
            "url": "https://cdn.reelfyme.com/brainrot-template/valorant/chunk-84.mp4",
            "durationSec": 30
          }
        ]
      }
    ]
  }
]

export function getGameplayCategory(id: string): GameplayCategory | undefined {
  return GAMEPLAY_CATALOG.find((c) => c.id === id)
}
